// Builds the static site for GitHub Pages into _site/.
// There is no bundling: the client is copied as-is, and only two things are
// generated from the GAME_SERVER_URL repository variable:
//   1. client/config.js  — the server URL the client connects to
//   2. the CSP meta tag's connect-src — so the page may talk only to that server
import fs from "node:fs";
import path from "node:path";

const raw = (process.env.GAME_SERVER_URL || "").trim();
if (!raw) {
    console.error("GAME_SERVER_URL is not set. Add it under Settings → Secrets and variables → Actions → Variables.");
    process.exit(1);
}
let url;
try {
    url = new URL(raw);
} catch {
    console.error(`GAME_SERVER_URL is not a valid URL: ${raw}`);
    process.exit(1);
}
if (url.protocol !== "https:") {
    console.error("GAME_SERVER_URL must start with https:// (production must use HTTPS/WSS).");
    process.exit(1);
}
const origin = url.origin; // drops any path/query
const wsOrigin = origin.replace(/^https:/, "wss:");

const out = "_site";
fs.rmSync(out, { recursive: true, force: true });
fs.cpSync("client", out, { recursive: true });

fs.writeFileSync(
    path.join(out, "config.js"),
    `// Generated by scripts/build-pages.mjs at deploy time.\nexport default { serverUrl: ${JSON.stringify(origin)} };\n`
);

const indexPath = path.join(out, "index.html");
const html = fs.readFileSync(indexPath, "utf8");
const updated = html.replace(/connect-src [^;"]*/, `connect-src 'self' ${origin} ${wsOrigin}`);
if (updated === html) {
    console.error("Could not find connect-src in index.html's CSP meta tag.");
    process.exit(1);
}
fs.writeFileSync(indexPath, updated);
fs.writeFileSync(path.join(out, ".nojekyll"), "");
console.log(`Built ${out}/ for server ${origin}`);
